# Generated by Django 3.0.9 on 2020-08-13 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('detection', '0002_detectionpagepsenetimage_detectionpageresultimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionpageintroimage',
            name='intro_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='detectionpagepsenetimage',
            name='psenet_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='detectionpageresultimage',
            name='result_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image'),
        ),
    ]
