# Generated by Django 3.0.9 on 2020-08-13 13:41

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_auto_20200813_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionpage',
            name='cor',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
