# Generated by Django 3.0.9 on 2020-08-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_detectionpage_cor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectionpage',
            name='cor',
        ),
        migrations.AddField(
            model_name='detectionpage',
            name='count',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='detectionpage',
            name='result',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
