# Generated by Django 3.0.9 on 2020-08-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0009_jointdetectionpageintroimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='jointdetectionpage',
            name='resnet_href',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
