# Generated by Django 3.0.9 on 2020-09-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0012_jointdetectionpagejointimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='jointdetectionpage',
            name='psenet_href',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
