# Generated by Django 3.0.9 on 2020-10-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0017_auto_20200916_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='persondetectionpage',
            name='name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
