# Generated by Django 3.0.9 on 2020-10-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0019_picturedetectionpage_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='jointdetectionpage',
            name='classification',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
