# Generated by Django 3.0.9 on 2020-10-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_uploadindexpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMG_Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='upload_person')),
            ],
        ),
    ]
